execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot1 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot1] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot1 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
