execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot14 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot14] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot14 
