execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot23 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot23] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot23 
