execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot28 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot28] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot28 
