execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot12 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot12] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot12 
