execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot20 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot20] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot20 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
