execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot24 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot24] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot24 
