execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot21 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot21] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot21 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
