execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot25 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot25] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot25 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
