execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot35 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot35] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot35 
