execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot11 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot11] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot11 
