execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot18 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot18] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot18 
