execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot17 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot17] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot17 
