execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot19 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot19] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot19 
