execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot5 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot5] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot5 
