execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot27 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot27] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot27 
