execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot6 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot6] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot6 
