execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot33 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot33] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot33 
