execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot30 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot30] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot30 
