execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot3 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot3] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot3 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
