execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot34 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot34] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot34 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
