execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot4 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot4] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot4 
