execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot8 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot8] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot8 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
