execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot2 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot2] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot2 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
