execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot32 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot32] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot32 
