execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot0 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot0] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot0 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
