execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot7 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot7] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot7 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
