execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AirInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AirInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GraniteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GraniteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedGraniteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedGraniteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DioriteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DioriteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedDioriteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedDioriteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AndesiteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AndesiteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PolishedAndesiteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PolishedAndesiteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DirtInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DirtInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoarseDirtInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoarseDirtInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PodzolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PodzolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodPlankInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodPlankInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakSaplingInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakSaplingInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedrockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedrockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingWaterInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingWaterInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillWaterInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillWaterInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowingLavaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowingLavaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StillLavaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StillLavaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GravelInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GravelInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CoalOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CoalOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpongeInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpongeInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WetSpongeInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WetSpongeInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LapisLazuliBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LapisLazuliBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DispenserInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DispenserInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledSandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledSandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothSandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothSandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NoteBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NoteBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BedInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BedInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoweredRailInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoweredRailInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DetectorRailInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DetectorRailInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StickyPistonInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StickyPistonInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobwebInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobwebInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadShrubInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadShrubInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FernInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FernInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DeadBushInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DeadBushInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PistonHeadInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PistonHeadInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackWoolInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackWoolInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DandelionInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DandelionInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PoppyInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PoppyInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueOrchidInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueOrchidInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AlliumInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AlliumInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AzureBluetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AzureBluetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedTulipInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedTulipInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeTulipInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeTulipInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteTulipInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteTulipInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkTulipInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkTulipInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OxeyeDaisyInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OxeyeDaisyInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GoldBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GoldBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSandstoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSandstoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleWoodenSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleWoodenSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleCobblestoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleCobblestoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleStoneBrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleStoneBrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleNetherBrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleNetherBrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleQuartzSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleQuartzSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TNTInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TNTInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BookshelfInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BookshelfInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossStoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossStoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObsidianInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObsidianInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TorchInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TorchInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FireInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FireInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MonsterSpawnerInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MonsterSpawnerInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChestInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChestInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneWireInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneWireInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DiamondBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DiamondBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CraftingTableInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CraftingTableInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WheatCropsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WheatCropsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FarmlandInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FarmlandInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FurnaceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FurnaceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BurningFurnaceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BurningFurnaceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StandingSignBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StandingSignBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LadderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LadderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RailInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RailInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedSignBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedSignBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LeverInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LeverInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StonePressurePlateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StonePressurePlateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenPressurePlateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenPressurePlateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowingRedstoneOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowingRedstoneOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(off)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(off)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneTorch(on)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneTorch(on)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneButtonInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneButtonInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SnowBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SnowBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CactusInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CactusInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SugarCanesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SugarCanesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JukeboxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JukeboxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherrackInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherrackInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SoulSandInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SoulSandInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlowstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlowstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherPortalInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherPortalInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Jacko'LanternInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Jacko'LanternInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CakeBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CakeBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(off)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(off)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneRepeaterBlock(on)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneRepeaterBlock(on)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenTrapdoorInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenTrapdoorInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBrickMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBrickMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBrickMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBrickMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBrickMonsterEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBrickMonsterEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyStoneBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyStoneBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CrackedStoneBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CrackedStoneBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledStoneBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledStoneBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownMushroomBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownMushroomBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedMushroomBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedMushroomBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronBarsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronBarsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PumpkinStemInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PumpkinStemInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MelonStemInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MelonStemInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=VinesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add VinesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrickStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrickStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StoneBrickStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StoneBrickStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MyceliumInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MyceliumInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilyPadInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilyPadInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherBrickStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherBrickStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnchantmentTableInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnchantmentTableInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrewingStandInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrewingStandInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CauldronInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CauldronInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndPortalFrameInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndPortalFrameInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DragonEggInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DragonEggInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(inactive)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(inactive)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneLamp(active)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneLamp(active)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleOakWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleOakWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleSpruceWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleSpruceWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleBirchWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleBirchWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleJungleWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleJungleWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleAcaciaWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleAcaciaWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleDarkOakWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleDarkOakWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OakWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OakWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CocoaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CocoaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SandstoneStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SandstoneStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EnderChestInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EnderChestInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireHookInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireHookInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TripwireInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TripwireInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EmeraldBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EmeraldBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CommandBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CommandBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeaconInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeaconInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CobblestoneWallInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CobblestoneWallInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MossyCobblestoneWallInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MossyCobblestoneWallInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FlowerPotInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FlowerPotInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CarrotsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CarrotsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PotatoesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PotatoesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WoodenButtonInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WoodenButtonInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MobHeadInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MobHeadInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AnvilInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AnvilInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=TrappedChestInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add TrappedChestInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(light)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(light)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WeightedPressurePlate(heavy)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WeightedPressurePlate(heavy)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(inactive)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(inactive)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneComparator(active)InSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneComparator(active)InSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DaylightSensorInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DaylightSensorInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedstoneBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedstoneBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherQuartzOreInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherQuartzOreInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HopperInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HopperInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledQuartzBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledQuartzBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PillarQuartzBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PillarQuartzBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=QuartzStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add QuartzStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ActivatorRailInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ActivatorRailInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DropperInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DropperInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackHardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackHardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackStainedGlassPaneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackStainedGlassPaneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakLeavesInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakLeavesInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakWoodStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakWoodStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SlimeBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SlimeBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BarrierInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BarrierInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=IronTrapdoorInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add IronTrapdoorInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PrismarineBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PrismarineBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkPrismarineInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkPrismarineInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SeaLanternInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SeaLanternInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HayBaleInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HayBaleInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackCarpetInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackCarpetInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=HardenedClayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add HardenedClayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlockofCoalInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlockofCoalInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PackedIceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PackedIceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SunflowerInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SunflowerInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LilacInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LilacInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleTallgrassInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleTallgrassInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LargeFernInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LargeFernInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RoseBushInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RoseBushInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PeonyInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PeonyInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Free-standingBannerInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Free-standingBannerInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=Wall-mountedBannerInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add Wall-mountedBannerInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=InvertedDaylightSensorInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add InvertedDaylightSensorInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChiseledRedSandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChiseledRedSandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SmoothRedSandstoneInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SmoothRedSandstoneInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DoubleRedSandstoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DoubleRedSandstoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedSandstoneSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedSandstoneSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceGateInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceGateInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaFenceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaFenceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=SpruceDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add SpruceDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BirchDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BirchDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=JungleDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add JungleDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=AcaciaDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add AcaciaDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=DarkOakDoorBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add DarkOakDoorBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndRodInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndRodInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusPlantInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusPlantInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChorusFlowerInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChorusFlowerInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurPillarInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurPillarInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurStairsInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurStairsInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurDoubleSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurDoubleSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpurSlabInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpurSlabInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndStoneBricksInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndStoneBricksInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BeetrootBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BeetrootBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrassPathInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrassPathInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=EndGatewayInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add EndGatewayInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RepeatingCommandBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RepeatingCommandBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ChainCommandBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ChainCommandBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=FrostedIceInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add FrostedIceInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagmaBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagmaBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=NetherWartBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add NetherWartBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedNetherBrickInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedNetherBrickInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BoneBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BoneBlockInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureVoidInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureVoidInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=ObserverInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add ObserverInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackShulkerBoxInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackShulkerBoxInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackGlazedTerracottaInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackGlazedTerracottaInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcreteInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcreteInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=WhiteConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add WhiteConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=OrangeConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add OrangeConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=MagentaConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add MagentaConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightBlueConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightBlueConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=YellowConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add YellowConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LimeConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LimeConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PinkConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PinkConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GrayConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GrayConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=LightGrayConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add LightGrayConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=CyanConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add CyanConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=PurpleConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add PurpleConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlueConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlueConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BrownConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BrownConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=GreenConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add GreenConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=RedConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add RedConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=BlackConcretePowderInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add BlackConcretePowderInSlot15 
execute @e[tag=copySlotTags] ~ ~ ~ execute @s[tag=StructureBlockInSlot15] ~ ~ ~ scoreboard players tag @e[tag=pasteSlotTags] add StructureBlockInSlot15 
scoreboard players tag @e[tag=pasteSlotTags] remove pasteSlotTags 
scoreboard players tag @e[tag=copySlotTags] remove copySlotTags 
