execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DispenserInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=ChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=FurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BurningFurnaceInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrewingStandInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=TrappedChestInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=HopperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DropperInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=WhiteShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=OrangeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=MagentaShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightBlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=YellowShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LimeShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PinkShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightGrayShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=CyanShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PurpleShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlueShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrownShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GreenShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=RedShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlackShulkerBoxInSlot4] add Slot4IsLootBlock 
