execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DispenserInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=ChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=FurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BurningFurnaceInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrewingStandInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=TrappedChestInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=HopperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DropperInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=WhiteShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=OrangeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=MagentaShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightBlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=YellowShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LimeShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PinkShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightGrayShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=CyanShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PurpleShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlueShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrownShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GreenShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=RedShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlackShulkerBoxInSlot8] add Slot8IsLootBlock 
