execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DispenserInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=ChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=FurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BurningFurnaceInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrewingStandInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=TrappedChestInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=HopperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DropperInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=WhiteShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=OrangeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=MagentaShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightBlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=YellowShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LimeShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PinkShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightGrayShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=CyanShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PurpleShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlueShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrownShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GreenShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=RedShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlackShulkerBoxInSlot0] add Slot0IsLootBlock 
