execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DispenserInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=ChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=FurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BurningFurnaceInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrewingStandInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=TrappedChestInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=HopperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DropperInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=WhiteShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=OrangeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=MagentaShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightBlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=YellowShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LimeShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PinkShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightGrayShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=CyanShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PurpleShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlueShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrownShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GreenShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=RedShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlackShulkerBoxInSlot1] add Slot1IsLootBlock 
