execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DispenserInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=ChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=FurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BurningFurnaceInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrewingStandInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=TrappedChestInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=HopperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=DropperInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=WhiteShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=OrangeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=MagentaShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightBlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=YellowShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LimeShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PinkShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=LightGrayShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=CyanShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=PurpleShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlueShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BrownShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=GreenShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=RedShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock1] ~ ~ ~ scoreboard players tag @e[name=block1Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock2] ~ ~ ~ scoreboard players tag @e[name=block2Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock3] ~ ~ ~ scoreboard players tag @e[name=block3Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock4] ~ ~ ~ scoreboard players tag @e[name=block4Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock5] ~ ~ ~ scoreboard players tag @e[name=block5Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock6] ~ ~ ~ scoreboard players tag @e[name=block6Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock7] ~ ~ ~ scoreboard players tag @e[name=block7Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock8] ~ ~ ~ scoreboard players tag @e[name=block8Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock9] ~ ~ ~ scoreboard players tag @e[name=block9Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
execute @s[tag=editBlock10] ~ ~ ~ scoreboard players tag @e[name=block10Memory,tag=BlackShulkerBoxInSlot3] add Slot3IsLootBlock 
