######################################################################################
# Function:		directional_probability
# Created By:	Jordan Hoffmann
# Date:			6/17/17
# Version:		1.12
# Description:	user interface for customizing the dungeon's direction probability
######################################################################################
#{"command":"tellraw @s %s","jobject":[{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Negative Z : ","color":"gray"},{"score":{"name":"zNegProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set zNegProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}],"jtemplate":"tellraw"}

scoreboard players tag @s add ui2
scoreboard players tag @s remove ui1
scoreboard players tag @s remove ui3
scoreboard players tag @s remove ui4
scoreboard players tag @s remove ui5
scoreboard players tag @s remove ui6
scoreboard players tag @s remove ui7

playsound minecraft:ui.button.click ambient @s ~ ~ ~
function dungeon_genorator:setup

tellraw @s ["",{"text":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n DIRECTIONAL PROBABILITY \n","color":"aqua","bold":true,"underlined":true}]

tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/xPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Positive X : ","color":"gray"},{"score":{"name":"xPosProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set xPosProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/xPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/xNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]    Negative X : ","color":"gray"},{"score":{"name":"xNegProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set xNegProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/xNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/yPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Positive Y : ","color":"gray"},{"score":{"name":"yPosProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set yPosProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/yPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/yNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]    Negative Y : ","color":"gray"},{"score":{"name":"yNegProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set yNegProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/yNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/zPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Positive Z : ","color":"gray"},{"score":{"name":"zPosProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set zPosProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/zPosProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
tellraw @s ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]    Negative Z : ","color":"gray"},{"score":{"name":"zNegProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set zNegProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]

tellraw @s ["",{"text":"\n              ","color":"gray"},{"text":"| Reload |","color":"gray","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/directional_probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]
tellraw @s ["",{"text":"               ","color":"gray"},{"text":"| Back |","color":"gray","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/probability_selector"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]

tellraw @s ["",{"text":" ##################### ","color":"aqua","bold":true,"underlined":true,"italic":false}]