######################################################################################
# Function:		directional_probability
# Created By:	Jordan Hoffmann
# Date:			6/17/17
# Version:		1.12
# Description:	user interface for customizing the dungeon's direction probability
######################################################################################
#{"command":"tellraw @s %s","jobject":[{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Negative Z : ","color":"gray"},{"score":{"name":"zNegProbability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set zNegProbability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/zNegProbability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}],"jtemplate":"tellraw"}

scoreboard players tag @s add ui6
scoreboard players tag @s remove ui1
scoreboard players tag @s remove ui2
scoreboard players tag @s remove ui3
scoreboard players tag @s remove ui4
scoreboard players tag @s remove ui5
scoreboard players tag @s remove ui7

playsound minecraft:ui.button.click ambient @s ~ ~ ~
function dungeon_genorator:setup

tellraw @s ["",{"text":"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n  VARIATION PROBABILITY  \n","color":"aqua","bold":true,"underlined":true}]

execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"    Mode: ","color":"gray"},{"text":"Random Distrobution","color":"light_purple","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/toggle/variation_mode"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"\n  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s1Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 1 : ","color":"gray"},{"score":{"name":"s1Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s1Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s1Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s2Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 2 : ","color":"gray"},{"score":{"name":"s2Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s2Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s2Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s3Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 3 : ","color":"gray"},{"score":{"name":"s3Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s3Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s3Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s4Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 4 : ","color":"gray"},{"score":{"name":"s4Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s4Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s4Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s5Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 5 : ","color":"gray"},{"score":{"name":"s5Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s5Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s5Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]
execute @e[type=armor_stand,name=editor,tag=!thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"  [","color":"gray"},{"text":" - ","color":"red","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/decrement/s6Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"decrement","color":"white"}]}}},{"text":"]     Variation 6 : ","color":"gray"},{"score":{"name":"s6Probability","objective":"controls"},"color":"light_purple","clickEvent":{"action":"suggest_command","value":"/scoreboard players set s6Probability controls 5"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click for command","color":"white"}]}}},{"text":"     [","color":"gray"},{"text":" + ","color":"green","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/increment/s6Probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"increment"}]}}},{"text":"]","color":"gray"}]

execute @e[type=armor_stand,name=editor,tag=thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"   Mode: ","color":"gray"},{"text":"Thematic Distrobution","color":"light_purple","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/toggle/variation_mode"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]
execute @e[type=armor_stand,name=editor,tag=thematic] ~ ~ ~ tellraw @a[tag=ui6] ["",{"text":"\n ~~ Feature Not Yet Added ~~","color":"red"}]


tellraw @s ["",{"text":"\n              ","color":"gray"},{"text":"| Reload |","color":"gray","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/variation_probability"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]
tellraw @s ["",{"text":"               ","color":"gray"},{"text":"| Back |","color":"gray","clickEvent":{"action":"run_command","value":"/execute @s ~ ~ ~ function dungeon_genorator:tellraw/probability_selector"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"click","color":"white"}]}},"insertion":"tellraw @s %s"}]

tellraw @s ["",{"text":" ##################### ","color":"aqua","bold":true,"underlined":true,"italic":false}]